name: "Build game release"

on:
  push: 
    tags:
      - "v*"

jobs:
  build:
    name: "Build game"
    runs-on: ubuntu-latest
    container:
      image: "barichello/godot-ci:3.5.1"

    strategy:
      matrix:
        target:
          - "Windows"
          - "MacOSX"
          - "LinuxX11"
          - "HTML5"

    steps:
      - name: "⬇️ Checkout repository"
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: "⚙️ Setup Godot templates"
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/3.5.1.stable ~/.local/share/godot/templates/3.5.1.stable
      
      - name: "⚙️ Setup Godot build directories"
        run: |
          mkdir -v -p export/${{ matrix.target }}/LD50/
          
      - name: "🏗️ Build game"
        run: |
          godot -v --export "${{ matrix.target }}"

      - name: "🌐 Create release"
        uses: ncipollo/release-action@v1.10.0
        with:
          artifactErrorsFailBuild: true
          artifacts: export/${{ matrix.target }}/*
          draft: true
          generateReleaseNotes: true
